export enum ESegment {
  HIGH_TIER_CUSTOMER = "HIGH_TIER_CUSTOMER",
  MID_HIGH_TIER_CUSTOMER = "MID_HIGH_TIER_CUSTOMER",
  MID_LOW_TIER_CUSTOMER = "MID_LOW_TIER_CUSTOMER",
  LOW_TIER_CUSTOMER = "LOW_TIER_CUSTOMER",
  NEW_CUSTOMER = "NEW_CUSTOMER",
}
